### ISSUE TITLE
Notice: Undefined property

### ISSUE THREAD

**Issue by tanolalano** [satispay/magento2-plugin#1]
I install version 1 of your module with no issue.
After I insert Security Bearer and enable the module.
On frontend when selecting Satispay payment option and clicking the button that redirect to satispay i get this error:
`Notice: Undefined property: stdClass::$checkout_url in ......./vendor/satispay/magento2-plugin/Controller/Satispay/Payment.php on line 50`
My conf. is:
Magento 2.1.8
php 7.0.18
Vernish 4
Redis 3.2
If you need other information I'm glad to help you.
Regards

**Comment by alessiodionisi** [comment]
Probably your security bearer is invalid or is not for sandbox / staging mode
