### ISSUE TITLE
Magento 2.2.6 error after module install

### ISSUE THREAD

**Issue by Samuel88** [satispay/magento2-plugin#11]
Without **setup_version="2.0.1"** on file **etc/modules.xml** every bin/magento command gives this error on Magento 2.2.6

`Attribute 'setup version' is missing for module 'Satispay_Satispay'`

**Comment by ebofi** [comment]
@Samuel88 I had applied a fix on modules.xml

**Comment by ghost** [comment]
I don't see the fix in actual version...

**Comment by cavalier79** [comment]
bump, I've also this issue on M2.2.11 and upgrade satispay from 1.2.4 to 2.0.1

**Comment by stvnmsh** [comment]
Now you have the setup_version on modules.xml file.
