### ISSUE TITLE
Can't install on fresh magento 2.3.5-p1

### ISSUE THREAD

**Issue by tanolalano** [satispay/magento2-plugin#13]
Error installing satispay on fresh magento 2.3.5-p1 installation

`composer require satispay/magento2-plugin

Using version ^2.0 for satispay/magento2-plugin
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - satispay/magento2-plugin 2.0.2 requires magento/framework >=100.0.0 -> no matching package found.
    - satispay/magento2-plugin 2.0.1 requires magento/framework >=100.0.0 -> no matching package found.
    - satispay/magento2-plugin 2.0.0 requires magento/framework 100.0.* -> no matching package found.
    - Installation request for satispay/magento2-plugin ^2.0 -> satisfiable by satispay/magento2-plugin[2.0.0, 2.0.1, 2.0.2].`

**Comment by stvnmsh** [comment]
Please make sure that plugin is installed in the correct folder and composer is updated.
