### ISSUE TITLE
Cart error

### ISSUE THREAD

**Issue by antonellorossi** [satispay/magento2-plugin#14]
Hello,
i have this problem with satispay plugin.
My cart load white page with this error 

`<b>Fatal error</b>:  Uncaught Error: Class 'SatispayGBusiness\Api' not found in /var/www.../Satispay.php:39`

How can i solve it?

Thanks

Antonello

**Comment by antonelloventurino** [comment]
Hello, 
I had the same problem, but I hope you already solved it now.
Anyway, you must install the dependency: satispay/gbusiness-api-php-sdk

P.S.: stesso nome mio: Antonello :-)

**Comment by stvnmsh** [comment]
@antonellorossi as said by your homonym you must install the dependency.
Follow the README for a proper installation.
