### ISSUE TITLE
Is this plugin compatible with Magento 2.2?

### ISSUE THREAD

**Issue by LucaGallinari** [satispay/magento2-plugin#18]
Hi, is this plugin compatible with Magento 2.2? Or better, is there a version/tag that supported 2.2?
In your official documentation it's stated that it's compatible with M2.3+ but in the composer.json of this repo there aren't any constraint on the Magento version. Moreover, there has been some issues of users that used (or even is using) successfully this plugin on Magento 2.2, like:
https://github.com/satispay/magento2-plugin/issues/7
https://github.com/satispay/magento2-plugin/issues/11

**Comment by stvnmsh** [comment]
The minimum tested and supported version is 2.3 (CE) - the plugin can be installed on previous versions anyway, but we do not provide an official support.
