### ISSUE TITLE
Module uses undefined API method

### ISSUE THREAD

**Issue by giacmir** [satispay/magento2-plugin#2]
You module uses `\SatispayOnline\Api::setClient` that is not present in the Api class anymore. You should either change the implementation on the Magento side or force an older api version in your composer.json.

Best practice it's to do both.

**Comment by alessiodionisi** [comment]
We are working on an update for this plugin, for now you can comment that line https://github.com/satispay/magento2-plugin/blob/master/Model/Payment.php#L60.

**Comment by giacmir** [comment]
Thanks @adnsio,  I can't comment that line because I'm using composer, but I made a preference for that.
