### ISSUE TITLE
Online refund missing

### ISSUE THREAD

**Issue by dadolun95** [satispay/magento2-plugin#21]
Online refund are missing (complete and partial), only offline refund is available on magento adminhtml.

**Comment by stvnmsh** [comment]
Refunds can be made from an invoice credit memo
https://developers.satispay.com/docs/magento-2#steps-to-refund-a-payment

**Comment by dadolun95** [comment]
Magento2 offers two types of refund with the credit memo: online and offline.
Satispay module uses only offline refund. Doing an offline refund on Magento2 doesn't make a real refund on satispay (cause it doesn't call any API).
My suggestion is to develop also the online refund calling satispay via API. The model class is already in place (as far as I remember) but isn't used at the moment.
Please make a check about this and reopen the issue.

**Comment by stvnmsh** [comment]
We can confirm that the online refund is available, please make sure the credit memo is opened from the invoice of the order and that the status of the order itself is "in processing" while performing this operation (if not it means the callback has not been received and the order has not been marked as paid with Satispay).
