### ISSUE TITLE
Deprecated functionality

### ISSUE THREAD

**Issue by micheledalonzo** [satispay/magento2-plugin#26]
Hi, on 2.4.6 & php 8.1 I have this error after setup:upgrade:
Deprecated Functionality: base64_encode(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/vendor/satispay/magento2-plugin/Block/Adminhtml/System/Config/ActivationCode.php

Is the plugin compatible with these releases? 
Thank you

**Comment by miscusi-marcoaceti** [comment]
Any updates on this?

**Comment by keeara** [comment]
@miscusi-marcoaceti @micheledalonzo 
Issue fixed in the latest version

**Comment by keeara** [comment]
Already fixed
