### ISSUE TITLE
Need Updated version for 2.1.x and Above.

### ISSUE THREAD

**Issue by NickyBass** [satispay/magento2-plugin#3]
Actually this plugin doesn't work with magento 2.1.3 and above. 
When you install it, the settings don't show up in the Payments section. 
May you update the plugin?, i have tried by myself but i didn't find the solution.
As you can see https://www.mageplaza.com/magento-2-create-payment-method/ there is some changes to do from the past.

**Comment by alessiodionisi** [comment]
The latest version has been tested on Magento 2.2.2
