### ISSUE TITLE
Errors in version 2.2.1

### ISSUE THREAD

**Issue by kionez** [satispay/magento2-plugin#34]
Today i update satispay/magento2-plugin module on my ecommerce but i noticed two errors:
- in Controller/Redirect/Index.php at line 16 there is a trailing comma wich causes a /vendor/composer/ClassLoader.php error running bin/magento setup:di:compile
- in composer.json the version is still 2.2.0

**Comment by keeara** [comment]
Hello, sorry for the incovenience, the composer version has been updated. Could you check again?
Thanks!

**Comment by keeara** [comment]
in Controller/Redirect/Index.php at line 16 there is a trailing comma wich causes a /vendor/composer/ClassLoader.php error running bin/magento setup:di:compile
> Supported from php 8
