### ISSUE TITLE
Error updating to 1.2

### ISSUE THREAD

**Issue by tanolalano** [satispay/magento2-plugin#4]
After setup:upgrade command Using the command "setup:di:compile" I get this error

```
XXXX@instance:~/apps/magento/htdocs$ php bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 40.0 MiBPHP Fatal error:  Cannot declare class SatispayOnline\Api, because the name is already in use in ....../vendor/satispay/magento2-plugin/includes/online-api-php-sdk/lib/Api.php on line 4
```

**Comment by alessiodionisi** [comment]
Try to remove the old composer dependency: `composer remove satispay/online-api-php-sdk`

**Comment by tanolalano** [comment]
I get Same error. Even if Updating to 1.2.2

**Comment by alessiodionisi** [comment]
Try to remove the old version and then reinstall everything using composer

**Comment by tanolalano** [comment]
Same error after remove from composer and reinstalling.

**Comment by alessiodionisi** [comment]
The latest version solve this problem

**Comment by tanolalano** [comment]
Confirm 1.2.3 solve the issue.
Thanks
