### ISSUE TITLE
Logged In Customer Magento 2.2.2

### ISSUE THREAD

**Issue by primisuimotori** [satispay/magento2-plugin#7]
Continue to Satispay button doesn't work with Logged In Customer Magento 2.2.2

**Comment by primisuimotori** [comment]
Solved

1) added in app/code/Satispay/Satispay/view/frontend/layout/checkout_index_index.xml at line 23 after last  `<item name="quipago" xsi:type="array">` this:

`<item name="isBillingAddressRequired" xsi:type="boolean">true</item>`

2) added in /app/code/Satispay/Satispay/view/frontend/web/template/payment/form.html al line 11 after `<div class="payment-method-content">` this code:

```
 <div class="payment-method-billing-address">
            <!-- ko foreach: $parent.getRegion(getBillingAddressFormName()) -->
            <!-- ko template: getTemplate() --><!-- /ko -->
            <!--/ko-->
  </div>
   <div class="checkout-agreements-block">
            <!-- ko foreach: $parent.getRegion('before-place-order') -->
                <!-- ko template: getTemplate() --><!-- /ko -->
            <!--/ko-->
    </div>
```

**Comment by stvnmsh** [comment]
Minimum supported version of Magento is 2.3
